import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: 'class',
  content: [
    './app/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './lib/**/*.{ts,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        surface: '#131314',
        'surface-dim': '#131314',
        'surface-bright': '#3a393a',
        'surface-variant': '#353436',
        'surface-tint': '#adc6ff',
        'surface-container-lowest': '#0e0e0f',
        'surface-container-low': '#1c1b1c',
        'surface-container': '#201f20',
        'surface-container-high': '#2a2a2b',
        'surface-container-highest': '#353436',
        background: '#131314',
        'on-surface': '#e5e2e3',
        'on-surface-variant': '#c2c6d6',
        'on-background': '#e5e2e3',
        primary: '#adc6ff',
        'primary-container': '#4d8eff',
        'primary-fixed': '#d8e2ff',
        'primary-fixed-dim': '#adc6ff',
        'on-primary': '#002e6a',
        'on-primary-container': '#00285d',
        'on-primary-fixed': '#001a42',
        'on-primary-fixed-variant': '#004395',
        'inverse-primary': '#005ac2',
        secondary: '#ffb0cd',
        'secondary-container': '#aa0266',
        'secondary-fixed': '#ffd9e4',
        'secondary-fixed-dim': '#ffb0cd',
        'on-secondary': '#640039',
        'on-secondary-container': '#ffbad3',
        'on-secondary-fixed': '#3e0022',
        'on-secondary-fixed-variant': '#8c0053',
        tertiary: '#d0bcff',
        'tertiary-container': '#a078ff',
        'tertiary-fixed': '#e9ddff',
        'tertiary-fixed-dim': '#d0bcff',
        'on-tertiary': '#3c0091',
        'on-tertiary-container': '#340080',
        'on-tertiary-fixed': '#23005c',
        'on-tertiary-fixed-variant': '#5516be',
        outline: '#8c909f',
        'outline-variant': '#424754',
        error: '#ffb4ab',
        'error-container': '#93000a',
        'on-error': '#690005',
        'on-error-container': '#ffdad6',
        'inverse-surface': '#e5e2e3',
        'inverse-on-surface': '#313031',
      },
      fontFamily: {
        headline: ['Inter', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Berkeley Mono', 'monospace'],
        mono: ['Berkeley Mono', 'monospace'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
    },
  },
  plugins: [],
};

export default config;
